# Generated by Django 5.2.10 on 2026-01-23 23:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('name', models.CharField(max_length=255, verbose_name='Nazwa dostawcy')),
                ('nip', models.CharField(blank=True, max_length=15, null=True, verbose_name='NIP')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Adres')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Numer telefonu')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': 'Dostawca',
                'verbose_name_plural': 'Dostawcy',
            },
        ),
    ]
