# Generated by Django 5.2.10 on 2026-01-23 11:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nazwa produktu')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='Kod SKU')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Opis')),
                ('current_stock', models.IntegerField(default=0, null=True, verbose_name='Aktualny stan')),
                ('min_threshold', models.IntegerField(default=5, null=True, verbose_name='Próg alarmowy')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': 'Produkt',
                'verbose_name_plural': 'Produkty',
            },
        ),
    ]
