# Generated by Django 5.2.10 on 2026-01-23 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_product_sku'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('action_type', models.CharField(choices=[('CREATE', 'Utworzenie'), ('UPDATE', 'Edycja'), ('DELETE', 'Usunięcie'), ('STOCK_ADJ', 'Zmiana stanu')], max_length=10)),
                ('previous_stock', models.IntegerField(default=None, null=True, verbose_name='Poprzedni stan')),
                ('current_stock', models.IntegerField(default=None, null=True, verbose_name='Aktualny stan')),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
