# Generated by Django 5.2.10 on 2026-01-27 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_completed_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-status', '-id']},
        ),
    ]
